### ISSUE TITLE
LinkedIn Image link .

### ISSUE THREAD

**Issue by suubh** [kritikaparmar-programmer/MyPortfolio#1]
Hey Kritika , your website looks great . 
- Only fix the LinkedIn Image link .
![Kritika Parmar 6-24-2021 7-42-01 PM](https://user-images.githubusercontent.com/47265493/123323075-a9ef5100-d552-11eb-93dd-971c51834044.png)

**Comment by kritikaparmar-programmer** [comment]
Thanks for pointing it out 😄
